name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ] # Akan jalan otomatis setiap kamu push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Mengatur kredensial git otomatis menggunakan Token Rahasia
          git remote add hf https://chicknug19:$HF_TOKEN@huggingface.co/spaces/chicknug19/aol-nlp
          
          # Memaksa git mengirimkan kode dari GitHub ke Hugging Face
          git push --force hf main