name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Push Backend to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd NLP_backend
          
          # ========================================================
          # OPERASI PEMBUANGAN BEBAN BERAT (HANYA DI DALAM ROBOT)
          # Ini TIDAK akan menghapus file di laptop/GitHub kamu!
          # ========================================================
          rm -rf nlp_dataset/
          rm -f *.keras
          rm -f *.pkl
          rm -f *.pickle
          
          # Sekarang folder ini hanya tersisa kodingan Python & IndoBERT
          
          git init
          git checkout -b main
          
          git config user.email "action@github.com"
          git config user.name "GitHub Action Bot"
          
          git lfs install
          # Karena model lain sudah dihapus, kita cukup track safetensors
          git lfs track "*.safetensors"
          
          git add .
          git commit -m "Deploy Backend to Hugging Face (Diet Ekstrem)"
          
          # Perintah --force di bawah ini akan mereset server Hugging Face
          # dan membersihkan sisa sampah 1 GB sebelumnya
          git push --force https://chicknug19:${HF_TOKEN}@huggingface.co/spaces/chicknug19/aol-nlp main