name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Push Backend to Hugging Face
        env:
          # Pastikan penamaan token sesuai dengan rahasia yang kamu buat di GitHub (HF_TOKEN)
          HF_TOKEN: ${{ secrets.HF_TOKEN }} 
        run: |
          cd NLP_backend
          
          git init
          git checkout -b main
          
          git config user.email "action@github.com"
          git config user.name "GitHub Action Bot"
          
          # Satpam LFS yang sudah kita lengkapi
          git lfs install
          git lfs track "*.safetensors"
          git lfs track "*.keras"
          git lfs track "*.pkl"
          git lfs track "*.pickle" 
          git lfs track "*.csv"
          git lfs track "*.xlsx"
          
          git add .
          git commit -m "Deploy Backend to Hugging Face with LFS"
          
          git push --force https://chicknug19:${HF_TOKEN}@huggingface.co/spaces/chicknug19/aol-nlp main